### ISSUE TITLE
WP_JSON_Posts_Controller should be WP_REST_Posts_Controller

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods-rest-api#55]
The class check to see if the WP REST API is active is currently looking at the old class name: `WP_JSON_Posts_Controller`

The new class name is: `WP_REST_Posts_Controller`

**Comment by sc0ttkclark** [comment]
Most "_JSON_" or "_json_" usage has been replaced with "_REST_" or "_rest_", like `register_rest_route( .... )`

**Comment by quasel** [comment]
https://github.com/pods-framework/pods-rest-api/issues/47  seems we missed some ;)

**Comment by quasel** [comment]
did take a look already  fixed in https://github.com/pods-framework/pods-rest-api/tree/feature/43-default-routes - the only branch wich is "sort of" working ^^
