### ISSUE TITLE
Pods REST API requires the core WordPress REST API be active.

### ISSUE THREAD

**Issue by parick1** [pods-framework/pods-rest-api#60]
WP version 4.3.1
PHP 5.5
PODS Version 2.5.5

1. I installed plugin WordPress REST API v2 and activated it.
2. Then download zip archive and installed plugin Pods REST API from https://github.com/pods-framework/pods-rest-api and activated it.

Now I see error “Pods REST API requires the core WordPress REST API be active”, but WP REST API plugin is already installed and activated.

Does it mean I need to wait until the WP REST API is included to WP core, not plugin. Would it be in WP 4.4 or 4.5?

**Comment by jimtrue** [comment]
@Shelob9 this came across the forums and I have no clue how to answer it since it looks like the Pods REST API is merging with Pods Core. Can you answer?

**Comment by Shelob9** [comment]
@parick1  This plugin was an experiment. We are moving on from it by merging this stuff into Pods 2.5.6.

See: 
https://github.com/pods-framework/pods/issues/3209
https://github.com/pods-framework/pods/pull/3184

**Comment by sandhya09** [comment]
@Shelob9,

Can you please let me know when PODS 2.5.6 is going to be release?
Im stuck there to connect pods and WP rest API?

**Comment by Shelob9** [comment]
@sandhya09 You can follow the progress of Pods 2.5.6 here: https://github.com/pods-framework/pods/milestones/Pods%202.5.6

**Comment by sandhya09** [comment]
I have tried 2.5.6-Beta , but its not working.
Do I have to wait for final release?
I have only install PODS 2.5.6 + WP REST API version2.
Is it compatible?

**Comment by sandhya09** [comment]
I have tried 2.5.6-Beta , but its not working.
Do I have to wait for final release?
I have only install PODS 2.5.6 + WP REST API version2.
Is it compatible?

**Comment by Shelob9** [comment]
@sandhya09 It's not in the current beta of 2.5.6 I wrote the pull request to add it. That pull request has not been merged.

**Comment by sandhya09** [comment]
Is this already merged? Or it will take time?
Or it will not going to merge?
Can you please advice me what I can do now so that I can use PODS + REST

**Comment by Shelob9** [comment]
@sc0ttkclark Will have to answer the when will it be merged question?

**Comment by sandhya09** [comment]
@Shelob9 
I have checked branch 2.x which include REST API support and still it is not working.
Do I have to include some extra steps to make is compatible?
Please let me know

**Comment by sc0ttkclark** [comment]
Pods REST API support requires the latest [Pods 2.6 RC 1](http://pods.io/latest/), the latest [WP REST API 2.0 Beta 7](https://github.com/WP-API/WP-API/releases/tag/2.0-beta7) and the [latest nightly release of WordPress 4.4](https://wordpress.org/download/nightly/).

**Comment by Shelob9** [comment]
It should actually work just fine with WordPress 4.3.1 or later  plus Pods
2.6 RC 1 <http://pods.io/latest/> and WP REST API 2.0 Beta 7
<https://github.com/WP-API/WP-API/releases/tag/2.0-beta7>

--
JoshPress.net <http://joshpress.net/>
CalderaWP.com <http://calderawp.com/>
@Josh412 <http://twitter.com/Josh412>


On 25 November 2015 at 10:28, Scott Kingsley Clark <notifications@github.com

**Comment by sc0ttkclark** [comment]
@Shelob9 is that tested? Just want to be sure

**Comment by Shelob9** [comment]
That is what I am testing with.

**Comment by sc0ttkclark** [comment]
Perfect, thanks!

**Comment by qrahaman** [comment]
Thanks, Gentlemen.  I have installed the latest builds per Scott's earlier directions.  Here's the route index I have per the screenshot.  Question:  Should I not see Pods routes along with its endpoints and arguments within the index?  Given this index, I know how to use it to pull up the JSON for posts, pages, users, etc.  How would I do it if I can't see the route for a Pod?
  
![screenshot 2015-11-25 09 00 24](https://cloud.githubusercontent.com/assets/1299653/11403913/2bed02de-9354-11e5-9821-88f5d6c297f6.png)

**Comment by sc0ttkclark** [comment]
Did you enable the routes for your post type / taxonomy Pods?

**Comment by qrahaman** [comment]
Hhhmmm, how does one do that, Scott?

**Comment by Shelob9** [comment]
I just went ahead and published the documentation for this feature:
http://pods.io/?post_type=documentation&p=192888

Should help clear up any confusion.

--
JoshPress.net <http://joshpress.net/>
CalderaWP.com <http://calderawp.com/>
@Josh412 <http://twitter.com/Josh412>


On 25 November 2015 at 12:45, Scott Kingsley Clark <notifications@github.com

**Comment by qrahaman** [comment]
Thanks, Josh!

**Comment by sc0ttkclark** [comment]
Updated link: http://pods.io/docs/build/extending-core-wordpress-rest-api-routes-with-pods/
